ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.55610"
    buffer_management_mode: "bootstrap_lossless"
    max_lossless_tc: "2"
    skip_pll_check: "false"
    mpic_enable: "false"
    mac_clk: "1340"
    sys_clk: "2000"
    ifc_clk: "1000"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"

  devports:
  - id: "0"
    sysport: "129"
    type: "cpu"
  - id: "1"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "15"
    speed: "200G"
    sysport: "1"
    type: "eth"
  - id: "2"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "15"
    speed: "200G"
    sysport: "5"
    type: "eth"
  - id: "3"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "14"
    speed: "200G"
    sysport: "9"
    type: "eth"
  - id: "4"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "14"
    speed: "200G"
    sysport: "13"
    type: "eth"
  - id: "5"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "13"
    speed: "200G"
    sysport: "17"
    type: "eth"
  - id: "6"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "13"
    speed: "200G"
    sysport: "21"
    type: "eth"
  - id: "7"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "12"
    speed: "200G"
    sysport: "25"
    type: "eth"
  - id: "8"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "12"
    speed: "200G"
    sysport: "29"
    type: "eth"
  - id: "9"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "11"
    speed: "200G"
    sysport: "33"
    type: "eth"
  - id: "10"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "11"
    speed: "200G"
    sysport: "37"
    type: "eth"
  - id: "11"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "10"
    speed: "200G"
    sysport: "41"
    type: "eth"
  - id: "12"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "10"
    speed: "200G"
    sysport: "45"
    type: "eth"
  - id: "13"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "9"
    speed: "200G"
    sysport: "49"
    type: "eth"
  - id: "14"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "9"
    speed: "200G"
    sysport: "53"
    type: "eth"
  - id: "15"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "8"
    speed: "200G"
    sysport: "57"
    type: "eth"
  - id: "16"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "8"
    speed: "200G"
    sysport: "61"
    type: "eth"
  - id: "17"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "7"
    speed: "200G"
    sysport: "65"
    type: "eth"
  - id: "18"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "7"
    speed: "200G"
    sysport: "69"
    type: "eth"
  - id: "19"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "6"
    speed: "200G"
    sysport: "73"
    type: "eth"
  - id: "20"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "6"
    speed: "200G"
    sysport: "77"
    type: "eth"
  - id: "21"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "5"
    speed: "200G"
    sysport: "81"
    type: "eth"
  - id: "22"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "5"
    speed: "200G"
    sysport: "85"
    type: "eth"
  - id: "23"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "4"
    speed: "200G"
    sysport: "89"
    type: "eth"
  - id: "24"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "4"
    speed: "200G"
    sysport: "93"
    type: "eth"
  - id: "25"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "3"
    speed: "200G"
    sysport: "97"
    type: "eth"
  - id: "26"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "3"
    speed: "200G"
    sysport: "101"
    type: "eth"
  - id: "27"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "2"
    speed: "200G"
    sysport: "105"
    type: "eth"
  - id: "28"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "2"
    speed: "200G"
    sysport: "109"
    type: "eth"
  - id: "29"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "1"
    speed: "200G"
    sysport: "113"
    type: "eth"
  - id: "30"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "1"
    speed: "200G"
    sysport: "117"
    type: "eth"
  - id: "31"
    fec: "KPFEC"
    lanes: "0:4"
    serdes_group: "0"
    speed: "200G"
    sysport: "121"
    type: "eth"
  - id: "32"
    fec: "KPFEC"
    lanes: "4:4"
    serdes_group: "0"
    speed: "200G"
    sysport: "125"
    type: "eth"
#  - id: "33"
#    fec: "NONE"
#    lanes: "0:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "33"
#    type: "mgmt 0"
#  - id: "34"
#    fec: "NONE"
#    lanes: "1:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "34"
#    type: "mgmt 1"
  isg:
  - id: "0"
    lane_swap: "01234765"
    rx_polarity: "00000111"
    tx_polarity: "10011110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "1"
    lane_swap: "21034567"
    rx_polarity: "00100111"
    tx_polarity: "10110101"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "2"
    lane_swap: "01236547"
    rx_polarity: "10100000"
    tx_polarity: "01100101"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "3"
    lane_swap: "01236547"
    rx_polarity: "01001001"
    tx_polarity: "10100110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "4"
    lane_swap: "01234567"
    rx_polarity: "10010000"
    tx_polarity: "10100001"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "5"
    lane_swap: "01234567"
    rx_polarity: "00100000"
    tx_polarity: "01100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "6"
    lane_swap: "01234765"
    rx_polarity: "11011000"
    tx_polarity: "00000101"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "7"
    lane_swap: "01234567"
    rx_polarity: "10000011"
    tx_polarity: "00010110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "8"
    lane_swap: "01234657"
    rx_polarity: "00001010"
    tx_polarity: "00011010"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "9"
    lane_swap: "01234567"
    rx_polarity: "00010000"
    tx_polarity: "10100100"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "10"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "00100111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "11"
    lane_swap: "01234567"
    rx_polarity: "01000001"
    tx_polarity: "00100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "12"
    lane_swap: "02134567"
    rx_polarity: "00001010"
    tx_polarity: "00010111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "13"
    lane_swap: "01234567"
    rx_polarity: "01001011"
    tx_polarity: "00111110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "14"
    lane_swap: "01236547"
    rx_polarity: "11000000"
    tx_polarity: "11011101"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "15"
    lane_swap: "01234567"
    rx_polarity: "01000010"
    tx_polarity: "11011000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
