#!/bin/sh
set -e
# Automatically added by dh_systemd_start/12.1.1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop '6512-32r-platform.service' '6512-32r-syseeprom.service' 'platform-modules-6512-32r.service' >/dev/null || true
fi
# End automatically added section
