#!/bin/sh

#DEVICE="/usr/share/sonic/device"
#PLATFORM=$(/usr/local/bin/sonic-cfggen -H -v DEVICE_METADATA.localhost.platform)


# Install sonic-platform package
#if [ -e $DEVICE/$PLATFORM/sonic_platform-1.0-py2-none-any.whl ]; then
#    pip install $DEVICE/$PLATFORM/sonic_platform-1.0-py2-none-any.whl
#fi

depmod -a
systemctl enable platform-modules-3306-32.service
systemctl start platform-modules-3306-32.service
