#!/bin/sh
set -e
# Automatically added by dh_installinit/12.1.1
if [ -x "/etc/init.d/sonic-platform-wistron-3306-32" ]; then
	invoke-rc.d sonic-platform-wistron-3306-32 stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.1.1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'platform-modules-3306-32.service' >/dev/null || true
fi
# End automatically added section
